denoising_steps:
- 1000
- 666
- 333
warp_denoising_step: true
ts_schedule: false
mixed_precision: true
seed: 42
image_or_video_shape:
- 1
- 16
- 15
- 44
- 80
num_frame_per_block: 3
context_noise: 0
mode: universal
causal: true

cache:
  local_attn_size: 8

timestep_shift: 5.0
model_config_path: configs/universal/config.json
